[[aerospike.aerospike-3]]
= Aerospike Support

Aerospike support contains a wide range of features which are summarized below.

* Spring configuration support using Java based @Configuration classes or an XML namespace for a Aerospike driver instance and replica sets
* CassandraTemplate helper class that increases productivity performing common Aerospike operations. 
* Exception translation into Spring's portable Data Access Exception hierarchy
* Feature Rich Object Mapping integrated with Spring's Conversion Service
* Annotation based mapping metadata but extensible to support other metadata formats
* Java based Query, Criteria, and Update DSLs
* Automatic implementation of Repository interfaces including support for custom finder methods.

[[aerospike-getting-started]]
== Getting Started

Spring Data Aerospike uses Java Client, Aerospike’s Java client enables you to build applications in Java that store and retrieve data from an Aerospike cluster. It contains both synchronous and asynchronous calls to the database.

The Java Client runs on any platform with Java 1.6 version and above.

First you need to set up a running Aerospike server.

To create a Spring project in STS go to File -> New -> Spring Template Project -> Simple Spring Utility Project -> press Yes when prompted. Then enter a project and a package name such as org.spring.aerospike.example.

Then add the following to pom.xml dependencies section.

[source,xml]
----
<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-aerospike</artifactId>
    <version>1.0.0.RELEASE</version>
  </dependency>

</dependencies>
----

Also change the version of Spring in the pom.xml to be

[source,xml]
----
<spring.framework.version>4.1.7</spring.framework.version>
----

You will also need to add the location of the Spring Milestone repository for maven to your pom.xml which is at the same level of your <dependencies/> element

[source,xml]
----
<repositories>
  <repository>
    <id>spring-milestone</id>
    <name>Spring Maven MILESTONE Repository</name>
    <url>http://repo.spring.io/libs-milestone</url>
  </repository>
</repositories>
----

The repository is also http://shrub.appspot.com/maven.springframework.org/milestone/org/springframework/data/[browseable here].

Create a simple Employee class to persist.

[source,java]
----
package org.springframework.data.aerospike.example;

/**
 *
 *
 * @author Peter Milne
 * @author Jean Mercier
 *
 */
public class Person {
	
	 private String id;

	 private String name;
	 private int age;

	 public Person(String id, String name, int age) {
	  this.id = id;
	  this.name = name;
	  this.age = age;
	 }

	 public String getId() {
	  return id;
	 }

	 public String getName() {
	  return name;
	 }

	 public int getAge() {
	  return age;
	 }

	 @Override
	 public String toString() {
	  return "Person [id=" + id + ", name=" + name + ", age=" + age + "]";
	 }

}
----

And a main application to run

[source,java]
----
package org.springframework.data.aerospike.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.aerospike.core.AerospikeTemplate;
import org.springframework.data.aerospike.repository.query.Criteria;
import org.springframework.data.aerospike.repository.query.Query;
import org.springframework.data.aerospike.example.data.Person;

import com.aerospike.client.AerospikeClient;
import com.aerospike.client.AerospikeException;
import com.aerospike.client.query.IndexType;

/**
 *
 *
 * @author Peter Milne
 * @author Jean Mercier
 *
 */
public class AerospikeApp {

	private static final Logger LOG = LoggerFactory
			.getLogger(AerospikeApp.class);

	/**
	 * @param args
	 */
	public static void main(String[] args) {

		try {
			String localhost = "127.0.0.1";
			AerospikeClient client = new AerospikeClient(null, localhost, 3000);
			AerospikeTemplate aerospikeTemplate = new AerospikeTemplate(client,
					"test");
			aerospikeTemplate.createIndex(Person.class,
					"Person_firstName_index", "name", IndexType.STRING);
			Person personSven01 = new Person("Sven-01", "ZName", 25);
			Person personSven02 = new Person("Sven-02", "QName", 21);
			Person personSven03 = new Person("Sven-03", "AName", 24);
			Person personSven04 = new Person("Sven-04", "WName", 25);

			aerospikeTemplate.delete(Person.class);

			aerospikeTemplate.insert(personSven01);
			aerospikeTemplate.insert(personSven02);
			aerospikeTemplate.insert(personSven03);
			aerospikeTemplate.insert(personSven04);

			Query query = new Query(
					Criteria.where("Person").is("WName", "name"));

			Iterable<Person> it = aerospikeTemplate.find(query, Person.class);
			int count = 0;
			Person firstPerson = null;
			for (Person person : it) {
				firstPerson = person;
				LOG.info(firstPerson.toString());
				System.out.println(firstPerson.toString());
				count++;
			}
		}
		catch (AerospikeException e) {
			e.printStackTrace();
		}

	}

}
----

Even in this simple example, there are a few things to observe.

* You can create an instance of AerospikeTemplate with a Aerospike Java Client, derived from the Cluster.
* Query syntax Criteria.where("Person").is("WName", "name")); where Person is the key and name is the index and Wname is what we are saexhing for

== Examples Repository

After the initial release of Spring Data Aerospike 1.0.0, we will start working on a showcase repository with full examples.

[[cassandra-connectors]]
== Connecting to Cassandra with Spring

[[cassandra-connectors.ext_properties]]
=== Externalize Connection Properties

Create a properties file with the information you need to connect to Cassandra. The contact points are keyspace are the minimal required fields, but port is added here for clarity.

We will call this aerospike.properties

[source]
----
aerospike.contactpoints=10.1.55.80,10.1.55.81
aerospike.port=3000
aerospike.keyspace=test
----

We will use spring to load these properties into the Spring Context in the next two examples.

[[aersospike-connectors.xmlconfig]]
=== XML Configuration

The XML Configuration elements for a basic Aerospike configuration are shown below. These elements all use default bean names to keep the configuration code clean and readable.

While this example show how easy it is to configure Spring to connect to Aerospike, there are many other options.  All of the Spring Data Aerospike method names and XML elements are named exactly (or as close as possible) like the configuration options on the driver so mapping any existing driver configuration should be straight forward.

[source,xml]
----
<?xml version='1.0'?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aersospike="http://www.springframework.org/schema/data/aersospike"
  xmlns:context="http://www.springframework.org/schema/context"
  xsi:schemaLocation="http://www.springframework.org/schema/cql http://www.springframework.org/schema/cql/spring-cql-1.0.xsd
    http://www.springframework.org/schema/data/aersospike http://www.springframework.org/schema/data/aersospike/spring-aersospike-1.0.xsd
    http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd">

  <!-- Loads the properties into the Spring Context and uses them to fill 
    in placeholders in the bean definitions -->
  <context:property-placeholder location="classpath:aersospike.properties" />

  <!-- REQUIRED: The Aerospike Cluster -->
  <aersospike:cluster contact-points="${aersospike.contactpoints}"
    port="${aersospike.port}" />

  <!-- REQUIRED: The Aerospike Session, built from the Cluster, and attaching 
    to a keyspace -->
  <aersospike:session keyspace-name="${aersospike.keyspace}" />

  <!-- REQUIRED: The Default Aerospike Mapping Context used by AerospikeConverter -->
  <aersospike:mapping />

  <!-- REQUIRED: The Default Aerospike Converter used by AerospikeTemplate -->
  <aersospike:converter />

  <!-- REQUIRED: The Aerospike Template is the building block of all Spring 
    Data Aerospike -->
  <aersospike:template id="aersospikeTemplate" />

  <!-- OPTIONAL: If you are using Spring Data Aerospike Repositories, add 
    your base packages to scan here -->
  <aersospike:repositories base-package="org.spring.aersospike.example.repo" />

</beans>
----


[source,java]
----

----

[[aerospike.auditing]]
== General auditing configuration

Auditing support is not available in the current version.

[[aerospike-template]]
== Introduction to AerospikeTemplate

[[aerospike-template.instantiating]]
=== Instantiating AerospikeTemplate

`AerospikeTemplate` should always be configured as a Spring Bean, although we show an example above where you can instantiate it directly. But for the purposes of this being a Spring module, lets assume we are using the Spring Container.

`AerospikeTemplate` is an implementation of `AerospikeTemplate`. You should always assign your `AerospikeTemplate` to its interface definition, `AerospikeTemplate`.

There are 2 easy ways to get a `AerospikeTemplate`, depending on how you load you Spring Application Context.

[float]
==== AutoWiring

[source,java]
----
@Autowired
private AerospikeTemplate aerospikeTemplate;
----

Like all Spring Autowiring, this assumes there is only one bean of type `AerospikeTemplate` in the `ApplicationContext`. 



