[[mongo.logging]]
= Logging support

An appender for Log4j is provided in the maven module "spring-data-aerospike-log4j". Note, there is no dependency on other Spring Aerospike modules, only the Aerospike driver.

[[mongodb:logging-configuration]]
== Aerospike Log4j Configuration

Here is an example configuration

[source]
----
log4j.logger.com.aerospike.helper=info, CONSOLE
#log4j.logger.com.aerospike.helper=debug, CONSOLE, FILE

# CONSOLE is set to be a ConsoleAppender using a PatternLayout.
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Threshold=TRACE
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%m%n

# FILE is set to be a ConsoleAppender using a PatternLayout.
#log4j.appender.FILE=org.apache.log4j.RollingFileAppender
#log4j.appender.FILE.File=aql.log
#log4j.appender.FILE.Threshold=TRACE
#log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
#log4j.appender.FILE.layout.ConversionPattern=%r %-5p %c{1} %x - %m%n

log4j.category.org.springframework.data.aerospike=INFO
log4j.category.org.springframework.transaction=INFO
----

The important configuration to look at aside from host and port is the database and collectionPattern. The variables year, month, day and hour are available for you to use in forming a collection name. This is to support the common convention of grouping log information in a collection that corresponds to a specific time period, for example a collection per day.

There is also an applicationId which is put into the stored message. The document stored from logging as the following keys: level, name, applicationId, timestamp, properties, traceback, and message.